IF OBJECT_ID('[dbo].[NewProcedure]') IS NOT NULL
	DROP PROCEDURE [dbo].[NewProcedure];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
--SET QUOTED_IDENTIFIER ON|OFF
--SET ANSI_NULLS ON|OFF
--GO
CREATE PROCEDURE [dbo].[NewProcedure] @parameter_name AS INT
-- WITH ENCRYPTION, RECOMPILE, EXECUTE AS CALLER|SELF|OWNER| 'user_name'
AS
BEGIN
    SELECT *
    FROM dbo.ArticleDescriptions;
END;
GO
