IF OBJECT_ID('[dbo].[prcGetCountries]') IS NOT NULL
	DROP PROCEDURE [dbo].[prcGetCountries];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
--SET QUOTED_IDENTIFIER ON|OFF
--SET ANSI_NULLS ON|OFF
--GO
CREATE PROCEDURE [dbo].[prcGetCountries]
 
-- WITH ENCRYPTION, RECOMPILE, EXECUTE AS CALLER|SELF|OWNER| 'user_name'
AS
    SELECT * FROM dbo.CountryCodes
GO
